### ISSUE TITLE
请问更新docker如何保存之前的设置？

### ISSUE THREAD

**Issue by dudt** [ruleeeer/ruleeeer-efb-wechat#1]
绑定到群组这些

**Comment by Jiannan-dev** [comment]
理论上文件应该在`/root/.ehforwarderbot/profiles/default/blueset.wechat`,你可以把这个文件夹下的文件复制出来，然后挂载数据卷启动新的docker试试，不过我没有具体试过，因为启动之后我就没有更新和关机过

**Comment by Jiannan-dev** [comment]
或者你可以尝试另一种更激进的方案，有个老哥写了个自动创建群组的efb,只不过需要权限，如果你感兴趣可以试试https://github.com/mlch911/efb-telegram-master/blob/master/readme_translations/zh_CN.rst#autotgmanagerconfig

**Comment by dudt** [comment]
> 或者你可以尝试另一种更激进的方案，有个老哥写了个自动创建群组的efb,只不过需要权限，如果你感兴趣可以试试https://github.com/mlch911/efb-telegram-master/blob/master/readme_translations/zh_CN.rst#autotgmanagerconfig

感谢！

**Comment by nonlog** [comment]
> 理论上文件应该在`/root/.ehforwarderbot/profiles/default/blueset.wechat`,你可以把这个文件夹下的文件复制出来，然后挂载数据卷启动新的docker试试，不过我没有具体试过，因为启动之后我就没有更新和关机过

请问, 我的并没有这个文件夹, 我想保留bot的绑定信息该怎样做? 下面这个链接我不太会弄, 失败了.
