### ISSUE TITLE
请问如何保留或者转移bot的绑定配置? 

### ISSUE THREAD

**Issue by nonlog** [ruleeeer/ruleeeer-efb-wechat#3]
我没有找到.ehforwarderbot这个文件夹

**Comment by Jiannan-dev** [comment]
建议参考 #1

**Comment by nonlog** [comment]
> 建议参考 #1

我看到了, 不过我试不成功, 不知道能不能找到配置文件复制下来

**Comment by Jiannan-dev** [comment]
> 我没有找到.ehforwarderbot这个文件夹

dockerfile的workdir就是`/root/.ehforwarderbot`下啊，不太可能没有这个文件夹吧,你找的绝对路径是什么？

<img width="481" alt="image" src="https://user-images.githubusercontent.com/70385062/228112154-3aebe839-3cf5-4f80-9081-bf777868653f.png">

**Comment by Jiannan-dev** [comment]
不过能迁移配置也是猜测，我没有真的试过，更加建议使用自动配置群组名称的那个，省的以后都要配置

**Comment by nonlog** [comment]
> > 我没有找到.ehforwarderbot这个文件夹
> 
> dockerfile的workdir就是`/root/.ehforwarderbot`下啊，不太可能没有这个文件夹吧,你找的绝对路径是什么？
> 
> <img alt="image" width="481" src="https://user-images.githubusercontent.com/70385062/228112154-3aebe839-3cf5-4f80-9081-bf777868653f.png">

![image](https://user-images.githubusercontent.com/61723005/228112693-942536d5-a55a-46d4-9291-a7267cda3323.png)
是这里没错吧.
好的, 我再去试试

**Comment by Jiannan-dev** [comment]
你这个路径好奇怪啊，运行docker的是什么系统？这个路径是运行的docker内部路径吗

**Comment by nonlog** [comment]
是Ubuntu. 这个是root目录吧. 我不是很懂, 比较小白

**Comment by Jiannan-dev** [comment]
我感觉你没有进入docker内部吧，你这是在宿主机上面

**Comment by Jiannan-dev** [comment]
> 获取容器Id
``` docker
docker ps -a
```
> 替换id进入容器内部（243c32535da7这一串）
``` docker
docker exec -it 243c32535da7 /bin/bash
```

**Comment by nonlog** [comment]
感谢作者, 找到了
![image](https://user-images.githubusercontent.com/61723005/228115866-f2457001-fb17-418a-af5c-81152a67ddb9.png)

**Comment by nonlog** [comment]
> 建议参考 #1

不好意思再打扰一下, 我使用efb主端从端的方式登录成功了, 按照https://github.com/mlch911/efb-telegram-master/blob/master/readme_translations/zh_CN.rst#autotgmanagerconfig 这里修改了config的flag, 填写了api, 但是并没有自动创建群组, 是不是还要什么操作?
